version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    reviewers:
      - "@astronomer/oss-integrations"

  - package-ecosystem: docker
    directory: /dev
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /dev
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /docs
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /scripts/airflow3
    schedule:
      interval: daily
